### ISSUE TITLE
Authentication for remote source

### ISSUE THREAD

**Issue by Anupam-** [andrewlock/NetEscapades.Configuration#15]
Hi @andrewlock  I have added **basic** and **bearer** authentication for **Remote Configuration**.
Please review the same here https://github.com/Anupam-/NetEscapades.Configuration/commit/beb541e6b0f72dd20ab043c6c8a958bf9b0c9952.

Please let me know your inputs.

**Comment by andrewlock** [comment]
Hi, @Anupam-, that looks great, thanks! 😄 

If you want to put together a PR we can discuss it there, but I'd only make a couple of changes - 

* Move the AuthenticationTypes enum into a different file
* Add a couple of unit tests around adding the Authorization Headers
* Configure and test it out in the sample project

Thanks again!

**Comment by Anupam-** [comment]
Hi @andrewlock, please have a look [https://github.com/Anupam-/NetEscapades.Configuration/commit/b6145f407c6fe090a466d78b4aef262602e3b4a0](url)
I have made appropriate changes in the forked repository.  Please let me know if I can create PR for the same.

**Comment by andrewlock** [comment]
Looks good to me, thanks! 

Feel free to create a PR

**Comment by andrewlock** [comment]
Fixed in #17
