### ISSUE TITLE
Configure YamlDotNet

### ISSUE THREAD

**Issue by aensidhe** [andrewlock/NetEscapades.Configuration#16]
I would like to have an ability to configure YamlParser that use your package.

Reasons:
- Injecting custom type converters
- Config validation

**Comment by andrewlock** [comment]
Hey, yeah that makes sense - but I'm not sure exactly what you would configure. 

In particular, type converters shouldn't come into it - the Yaml configuration loader reads everything as strings. You would need to hook into the ASP.NET Core Options framework if you want to do custom type convertion/binding.

Similarly, config validation doesn't really fit in this package. The ASP.NET Core config system is designed to allow loading from multiple partial files - individually the configuration might not be valid, but when combined with other JSON files, environment variables etc the final configuration might be valid.

**Comment by aensidhe** [comment]
Hm. I have this code:
````
services.Configure<OptionsClass>(x => this.Configuration.GetSection("SectionName").Bind(x));
````

And for validation I should plug into .net core configuration system?

**Comment by andrewlock** [comment]
Yeah, the typical approach is to validate inside the _consumer_ of your options object. So for example: 

```c#
public class MyClass
{
    private readonly OptionsClass _options;
    public MyClass(IOptions<OptionsClass> optionsAccessor)
    {
        _options = optionsAccessor.Value;
       if(_options.SomeValue < 0)
           throw new ArgumentException("OptionsClass.SomeValue must be greater than zero";
    }
}
```

Also, just another quick tip, you can simplify your configuration code to:

```c#
services.Configure<OptionsClass>(Configuration.GetSection("SectionName"));
```

If you add a reference to the _Microsoft.Extensions.Options.ConfigurationExtensions_ package in your project

**Comment by aensidhe** [comment]
I wanted to validate that config has keys to find misprints in keys. I'll try to work around that problem. Fill free to close issue, it is not related to your repo.

Thank you for your help.

**Comment by andrewlock** [comment]
No problem, thanks
