### ISSUE TITLE
Update YamlDotNet to 6.0.0

### ISSUE THREAD

**Issue by BobVul** [andrewlock/NetEscapades.Configuration#39]
This is a similar situation to #26.

With the YamlDotNet 6.0.0 release switching to strong named (signed) assemblies, they are now incompatible with pre-6.0.0 releases. Binding redirects are not generated automatically, and likely don't work at all between the two.

Please consider updating to YamlDotNet 6.0.0. Note that this will likely be a breaking change if any projects are depending on pre-6.0.0 - they would be forced to stay on an older version of NetEscapades.Configuration.Yaml, until they update YamlDotNet.

Since 6.0.0 is strong named, future YamlDotNet releases with the same public key should have binding redirects automatically generated by NuGet, so this should not be a problem again. (Maybe. I'm not that familiar with how the auto-generation works.)

**Comment by BobVul** [comment]
Current YamlDotNet is 6.1.2, but it shouldn't really matter which 6.x.x this depends on.

**Comment by andrewlock** [comment]
Urgh, god, I hate strong naming. Thanks for flagging it, I'll update soon!

**Comment by andrewlock** [comment]
Oops, completely forgot about this issue 😳 I've merged a fix to master, will push an update to NuGet in the next couple of days
