### ISSUE TITLE
Validation not working with .Net Core 3 WPF application

### ISSUE THREAD

**Issue by AllanMichaelsen** [andrewlock/NetEscapades.Configuration#51]
I have a WPF app that i reworte for .Net Core 3 but I can't get the validation to work.

The setup is as following:
App.xaml.cs
` 
 public partial class App
  {
    public App()
    {
      var configurationHost = Environment.GetEnvironmentVariable("ConfigurationHost") ?? "http://localhost";

      var hostBuilder = Host.CreateDefaultBuilder()
       .ConfigureAppConfiguration((context, builder) =>
        {
          context.HostingEnvironment.EnvironmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Development";
          builder.AddAppSettingsJsonFiles(context.HostingEnvironment.EnvironmentName);
        })
       .ConfigureServices((hostContext, services) =>
        {
          services.UseConfigurationValidation();
          services.ConfigureValidatableSetting<Settings>(hostContext.Configuration.GetSection(nameof(Settings)));
        });
      host = hostBuilder.Build();
    }

    protected override async void OnStartup(StartupEventArgs e)
    {
      base.OnStartup(e);
      await host.StartAsync();

      Settings = host.Services.GetRequiredService<Settings>();
    }
`

The Settings are added to the DI, but the validation never runs. Any ideas?

**Comment by andrewlock** [comment]
Hi, thanks for trying it out. The _Configuration.Validation_ library works specifically with ASP.NET Core currently. It uses an `IStartupFilter` to run code when the web server starts. I should definitely update that approach to work with the generic host (and I can relatively easy [thanks to this](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-3/)). 

For now, as a work around, you can do the validation manually in `OnStartup`:

```csharp
protected override async void OnStartup(StartupEventArgs e)
{
  base.OnStartup(e);
  await host.StartAsync();

  var validatables = host.Services.GetRequiredServices<IValidatable>();
  foreach (var validatableObject in _validatableObjects)
  {
      validatableObject.Validate(); // Will throw if not valid
  }

  Settings = host.Services.GetRequiredService<Settings>();
}
```

I hope that helps - I'll leave this issue open for now and update the library to support the generic host builder explicitly.

Thanks!

**Comment by AllanMichaelsen** [comment]
That works like a charm until generic host support is ready. Thank you for swift response. :-)

**Comment by andrewlock** [comment]
No problem, glad it worked! 🙂
