### ISSUE TITLE
Allow name conventions

### ISSUE THREAD

**Issue by galvesribeiro** [andrewlock/NetEscapades.Configuration#58]
Hello!

I'm trying to use your package but I'm struggling to map a YAML file that uses "_"-notation to the `IOptions<T>` options class that uses CamelCase in C#.

I was researching how that would be done and found out on [this issue](https://github.com/aaubry/YamlDotNet/issues/344#issuecomment-414957984) that it is possible to specify the convention to YamlDotNet.

However, your package doesn't expose that and the `YamlConfigurationFileParser` is created outside DI so can't actually inject the convention.

Is that possible for you to update the package to support specifying the convention? We are blocked on using it because we have legacy YAML files that use "_"-notation which is shared with the .Net application.

Thanks!

**Comment by andrewlock** [comment]
Hi, I was just looking at this, and unfortunately I don't think this will work. The issue you link shows how to deserialize a YAML file _directly_ to a .NET class, but that's not how the .NET Core config system (and `IOptions<>`) works. 

The .NET Config reads the YAML file as "raw" strings, and stores them in a string dictionary. The configuration binder then translates those strings into properties on the IOptions. 

There's no facility for translating the string keys that are read from the YAML file _before_ their inserted into the `IConfiguration` dictionary, that's not something that these libraries generally have as far as I know. 

Other options include binding "manually" to an `IOptions<>` instance and deserializing the YAML  file directly, as described in the link you provided. The latter is probably the easiest option!

**Comment by galvesribeiro** [comment]
Yeah, I was about to write back here. Yes, this is not possible unfortunately... I wish the configuration binder was exposed somehow so we could hook at it.

Thanks!
