### ISSUE TITLE
AddYamlFile with full path. But provider.Source.Path is only the file name without path

### ISSUE THREAD

**Issue by szmcdull** [andrewlock/NetEscapades.Configuration#64]
```c#
builder.AddYamlFile("/full/path/config.yaml", optional: false, reloadOnChange: false);
config = builder.Build();
Console.WriteLine(config.Providers.First().Source.Path) // print: config.yaml
```

**Comment by andrewlock** [comment]
I don't think this behaviour is specific to the `AddYamlFile()` extension method? For example `AddJsonFile()` behaves the same way right? In both cases, this is handled by the base [FileConfigurationProvider](https://github.com/dotnet/runtime/blob/ff74f55422/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs)?
