### ISSUE TITLE
YamlDotNet maintenance

### ISSUE THREAD

**Issue by jpenniman** [andrewlock/NetEscapades.Configuration#71]
Hi Andrew.  With YamlDotNet going on hold and in danger of being abandoned, do you have any plans to take it over or becoming a maintainer?  I use your Yaml configuration provider for many projects, including at work.

I'm considering offering my time (though limited) as a maintainer for YamlDotNet. Just curious if you have any plans.

https://github.com/aaubry/YamlDotNet/discussions/689

**Comment by devantler** [comment]
Hey, I am just following up here. Is the project still maintained? If not, does anyone know an alternative way to use YAML with app settings? :-)

**Comment by andrewlock** [comment]
Sorry for the delay @jpenniman!

> With YamlDotNet going on hold and in danger of being abandoned, do you have any plans to take it over or becoming a maintainer

Nope! If you have the desire, feel free, and I'll be happy to update this library with the latest 🙂 

> Is the project still maintained

Yes and no - I don't personally use it, but will address issues as they arise to work with the latest versions of .NET, but frankly, nothing's changed for years, so for the most part, it's "done"!

**Comment by devantler** [comment]
Thanks for reaching out, Andrew! It doesn't look like YamlDotNet is going out of maintenance any longer, but it is ahead with a few versions. The latest is 13.0.1, and this package is targeting 11.2.1. Is it possible for you to do a package bump of various packages to include the newest features?

**Comment by andrewlock** [comment]
Yep, no problem, done a bump here: https://github.com/andrewlock/NetEscapades.Configuration/pull/74

I'll try and get a release done shortly

**Comment by andrewlock** [comment]
Ok, that's been released as 3.0.0, so hopefully that'll do for now🙂  I'll close this issue for now, but feel free to open a new issue if you notice movement on the yamldotnet side!

**Comment by devantler** [comment]
Awesome, thank you so much! 😃
