### ISSUE TITLE
Major release 3.0

### ISSUE THREAD

**Issue by thedmi** [andrewlock/NetEscapades.Configuration#75]
Hi

I see that you've released 3.0.0. Thanks a lot for your continued effort with this library.

Is there any list of breaking changes when updating from 2.x to 3? I've reviewed the contained commits but failed to grasp where breaking changes might come from.

**Comment by andrewlock** [comment]
Hi, the breaking changes was because I bumped there version of YamlDotnet used by the library. It's very unlikely this will cause any problems, but it was a technically breaking change 🙂

**Comment by thedmi** [comment]
Thanks a lot for the clarification
