### ISSUE TITLE
Please add ASPNetCore support

### ISSUE THREAD

**Issue by Stefan-Z-Camilleri** [andrewlock/NetEscapades.Configuration#8]
From what I see, it should be as simple as upgrading to YamlDotNet 4.2.0

**Comment by andrewlock** [comment]
Sorry, I'm not sure I understand - this project t is only for ASP.NET core! 

What is it you're  trying to do? Do you have an example?

**Comment by Stefan-Z-Camilleri** [comment]
Well, this will only currently work on a windows machine that has .Net installed since its dependency on YamlDotNet 3.x requires that.

Meaning that you cannot install this on say linux or macOS.

For it to be fully core compliant it should not reference anything that has dependencies on non .NETStandard libraries.

In this case, the fix is simple, just upgrade to YamlDotNet 4.x

I've actually copied your code and replaced the dependency already, and it's working fine on both linux and macOs.

Other than this dependency issue, this code is great.

**Comment by andrewlock** [comment]
Wow, thanks, I can't believe I hadn't noticed it wasn't netstandard before - I probably knew at one point, but it completely slipped my mind!

I'll get that fixed and updated asap - thanks for flagging it

**Comment by andrewlock** [comment]
I've uploaded a beta package to my myget field which should fix this. I had to update a whole load of the build process, so I wonder if it would be possible for you give this nuget package a test in your project?
 https://www.myget.org/feed/andrewlock-ci/package/nuget/NetEscapades.Configuration.Yaml

If not, no problem, it was just in case :)

**Comment by Stefan-Z-Camilleri** [comment]
My pleasure @andrewlock , I will do so over the weekend.  I'll plug out my code and test with yours instead.

Thank you for fixing it so quickly!

**Comment by andrewlock** [comment]
FYI @Stefan-Z-Camilleri, I just pushed a new version to NuGet, 1.3.0

**Comment by Stefan-Z-Camilleri** [comment]
Thank you @andrewlock , admittedly I had started to test it and just got side-tracked.  I'll now just test the official release version and get rid of my version.

Cheers!
