### ISSUE TITLE
.NET 8 FileConfigurationProvider implementation change causes TestStreamHelpers raise exception

### ISSUE THREAD

**Issue by payphonepf** [andrewlock/NetEscapades.Configuration#80]
the latest .net 8 FileConfiguratinoProvider *Load(bool reload)* method implementation change causes *Add* YamlConfigurationSource to ConfigurationBuilder throwing NotImplementException from TestStreamHelpers.

the old FileConfigurationProvider implementation:
![image](https://github.com/andrewlock/NetEscapades.Configuration/assets/22732270/362b2311-2c2a-4935-af5a-37d1298a4ac5)

the new FileConfigurationProvider implementation: 
![image](https://github.com/andrewlock/NetEscapades.Configuration/assets/22732270/4316506d-673b-4560-8d11-296563854a25)

**Comment by andrewlock** [comment]
Do you have a repro for the error? All the tests pass on .NET 8, so I'm just trying to understand when this is failing for you?

**Comment by payphonepf** [comment]
Sorry, the repo is none-public, but the unit test case arrange section are like below.
```
string xml = """some yaml"""
var ymlConfigResource = new YamlConfigurationSource {FileProvider = TestStreamHelpers.StringToFileProvider(yml)};
var configuration = new ConfigurationBuilder()
    .Add(ymlConfigResource)
    .AddInMemoryCollection(new Dictionary<string, string?> {["key"] = "value"})
    .Build();
```

**Comment by andrewlock** [comment]
Sorry, I still can't reproduce this...


I tried adding this test case, but it passes in all cases 🤔

```csharp
[Fact]
public void Issue80()
{
    var yml = "Test: test";
    var ymlConfigResource = new YamlConfigurationSource { FileProvider = TestStreamHelpers.StringToFileProvider(yml) };
    var config = new ConfigurationBuilder()
        .Add(ymlConfigResource)
        .Build();
    
    Assert.Equal("test", config["Test"]);
}
```

But also:
- Isn't this a problem with `TestStreamHelpers`? That's not a type shipped with the YamlConfiguration provider (I just use it for testing) so did you write that?
- Have you considered using `AddYamlStream()` if you want to read from a stream instead of a file?
- Is this just a problem in your tests where you're using the helper, or are you seeing real issues in production code?

Thanks!

**Comment by payphonepf** [comment]
yes, I copy the `TestStreamHelper` for unit test purposes. I rollback the change related to `PhysicalPath` back to throw *NotImplementException* again and the unit test still passed. 
And I debug and step into the `FileConfigurationProvider` and the implementation seems is same as the first screenshot in .net 6. 
I can't reproduce the unit test failure case in codebase now. But this `PhysicalPath` issue causes the unit test failures on multiple PC on Nov 27th.
Thanks for your response. Will close this issue.
